import { useQuery } from '@tanstack/react-query'
import { Activity, AlertTriangle, Beaker, Bot, Boxes, ChevronRight, CircleDot, Database, FileSearch, Gauge, Hexagon, RadioTower, Search, Settings, ShieldAlert, ShieldCheck } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
type Alert = { id:number; timestamp:string; severity:string; source:string; destination:string; destination_port:number; protocol:string; detection:string; model_probability:number|null; status:string }
type Dashboard = { data_label:string; metrics:Record<string,number|null>; alerts_by_severity:Record<string,number>; alerts_by_protocol:{name:string;value:number}[]; alerts_over_time:{time:string;alerts:number}[]; recent_alerts:Alert[] }
const nav = [
  ['Overview', Gauge], ['SECURITY OPERATIONS', null], ['Alerts', ShieldAlert], ['Incidents', Boxes], ['Network Events', RadioTower],
  ['DETECTION', null], ['Detection Rules', FileSearch], ['MITRE ATT&CK', Hexagon], ['AI & EXPLAINABILITY', null],
  ['Explainability', Activity], ['Model Predictions', CircleDot], ['AI Assistant', Bot], ['RESEARCH', null],
  ['Experiments', Beaker], ['Model Comparison', Activity], ['Dataset', Database], ['Error Analysis', AlertTriangle], ['Model Monitoring', Gauge],
  ['SYSTEM', null], ['Settings', Settings],
] as const
const severityColor:Record<string,string> = { Critical:'#ef4444', High:'#f97316', Medium:'#f59e0b', Low:'#3b82f6', Informational:'#64748b' }

function Sidebar(){ return <aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={22}/></div><div><strong>SENTINEL XAI</strong><span>SOC ASSISTANT</span></div></div><nav>{nav.map(([label,Icon])=>Icon?<button className={label==='Overview'?'active':''} key={label}><Icon size={16}/><span>{label}</span>{label==='Alerts'&&<b>4</b>}</button>:<p key={label}>{label}</p>)}</nav><div className="system"><i></i><div><strong>LOCAL SYSTEM</strong><span>Evidence pipeline online</span></div></div></aside> }
function Metric({label,value,icon:Icon,tone}:{label:string,value:string|number,icon:any,tone:string}){return <article className="metric"><div><span>{label}</span><strong>{value}</strong></div><div className="metric-icon" style={{color:tone,background:`${tone}18`}}><Icon size={20}/></div></article>}
const shortTime=(v:string)=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})

export default function App(){
 const {data,error,isLoading}=useQuery<Dashboard>({queryKey:['dashboard'],queryFn:async()=>{const r=await fetch(`${API}/dashboard`);if(!r.ok)throw new Error('API unavailable');return r.json()}})
 const fallback:Dashboard={data_label:'SYNTHETIC DEMO DATA',metrics:{active_alerts:0,critical_alerts:0,high_alerts:0,open_incidents:0,events_analyzed:0,average_model_confidence:null},alerts_by_severity:{Critical:0,High:0,Medium:0,Low:0,Informational:0},alerts_by_protocol:[],alerts_over_time:[],recent_alerts:[]}
 const d=data||fallback; const severityData=Object.entries(d.alerts_by_severity).map(([name,value])=>({name,value})).filter(x=>x.value)
 return <div className="app"><Sidebar/><main><header><div><span className="eyebrow">SECURITY OPERATIONS</span><h1>Command overview</h1><p>Evidence-led monitoring across your network environment</p></div><div className="header-actions"><button className="search"><Search size={17}/>Search events, alerts, IPs <kbd>⌘ K</kbd></button><button className="live"><i/> LIVE</button><div className="avatar">AN</div></div></header>
 <div className="demo"><Beaker size={16}/><strong>{d.data_label}</strong><span>Illustrative events and deterministic rule evidence only. No trained model metrics are displayed.</span></div>
 {error&&<div className="error">Backend unavailable. Start the API to load demo evidence.</div>}
 <section className="metrics"><Metric label="ACTIVE ALERTS" value={isLoading?'—':d.metrics.active_alerts||0} icon={ShieldAlert} tone="#60a5fa"/><Metric label="CRITICAL" value={d.metrics.critical_alerts||0} icon={AlertTriangle} tone="#ef4444"/><Metric label="HIGH SEVERITY" value={d.metrics.high_alerts||0} icon={Activity} tone="#f97316"/><Metric label="OPEN INCIDENTS" value={d.metrics.open_incidents||0} icon={Boxes} tone="#a78bfa"/><Metric label="EVENTS ANALYZED" value={d.metrics.events_analyzed||0} icon={RadioTower} tone="#22d3a6"/></section>
 <section className="charts"><article className="panel wide"><div className="panel-head"><div><span>DETECTION ACTIVITY</span><h2>Alerts over time</h2></div><button>Last 24 hours⌄</button></div><ResponsiveContainer width="100%" height={220}><AreaChart data={d.alerts_over_time}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3b82f6" stopOpacity={.35}/><stop offset="1" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1b2638" vertical={false}/><XAxis dataKey="time" stroke="#64748b" tickLine={false}/><YAxis stroke="#64748b" allowDecimals={false} tickLine={false}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/><Area type="monotone" dataKey="alerts" stroke="#60a5fa" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></article>
 <article className="panel"><div className="panel-head"><div><span>RISK PROFILE</span><h2>Alerts by severity</h2></div></div><div className="donut"><ResponsiveContainer width="52%" height={190}><PieChart><Pie data={severityData} dataKey="value" innerRadius={57} outerRadius={78} paddingAngle={3}>{severityData.map(x=><Cell key={x.name} fill={severityColor[x.name]}/>)}</Pie><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/></PieChart></ResponsiveContainer><div className="legend">{severityData.map(x=><div key={x.name}><i style={{background:severityColor[x.name]}}/><span>{x.name}</span><b>{x.value}</b></div>)}</div></div></article>
 <article className="panel"><div className="panel-head"><div><span>TRAFFIC CONTEXT</span><h2>Alerts by protocol</h2></div></div><ResponsiveContainer width="100%" height={190}><BarChart data={d.alerts_by_protocol} layout="vertical"><CartesianGrid stroke="#1b2638" horizontal={false}/><XAxis type="number" stroke="#64748b" allowDecimals={false}/><YAxis dataKey="name" type="category" stroke="#94a3b8" width={45}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/><Bar dataKey="value" fill="#22d3a6" radius={[0,5,5,0]} barSize={18}/></BarChart></ResponsiveContainer></article></section>
 <section className="panel table-panel"><div className="panel-head"><div><span>INVESTIGATION QUEUE</span><h2>Recent alerts</h2></div><button className="link">View all alerts <ChevronRight size={15}/></button></div><div className="table-wrap"><table><thead><tr><th>TIME</th><th>SEVERITY</th><th>NETWORK PATH</th><th>PROTOCOL</th><th>DETECTION & EVIDENCE</th><th>CONFIDENCE</th><th>STATUS</th><th></th></tr></thead><tbody>{d.recent_alerts.map(a=><tr key={a.id}><td>{shortTime(a.timestamp)}</td><td><span className={`badge ${a.severity.toLowerCase()}`}><i/>{a.severity}</span></td><td><strong>{a.source}</strong><span className="arrow">→</span>{a.destination}:{a.destination_port}</td><td><code>{a.protocol}</code></td><td><strong>{a.detection}</strong><small>Deterministic demo rule</small></td><td>{a.model_probability===null?<span className="na">Not ML</span>:`${Math.round(a.model_probability*100)}%`}</td><td><span className="status">{a.status}</span></td><td><ChevronRight size={16}/></td></tr>)}{!d.recent_alerts.length&&<tr><td colSpan={8} className="empty">{isLoading?'Loading evidence…':'No alerts available.'}</td></tr>}</tbody></table></div></section>
 <footer><span>Milestone 1 · Research platform foundation</span><span>Model metrics: <b>not yet available</b></span></footer></main></div>
}
