import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, AlertTriangle, Beaker, Bot, Boxes, CheckCircle2, ChevronRight, CircleDot, Database, FileSearch, FileUp, Gauge, Hexagon, Menu, RadioTower, Search, Settings, ShieldAlert, ShieldCheck, UploadCloud, X, XCircle } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
type Alert = { id:number; timestamp:string; severity:string; source:string; destination:string; destination_port:number; protocol:string; detection:string; model_probability:number|null; status:string }
type Dashboard = { data_label:string; metrics:Record<string,number|null>; alerts_by_severity:Record<string,number>; alerts_by_protocol:{name:string;value:number}[]; alerts_over_time:{time:string;alerts:number}[]; recent_alerts:Alert[] }
type NetworkEvent = { id:number;timestamp:string;src_ip:string;dst_ip:string;src_port:number;dst_port:number;protocol:string;duration:number;packets:number;bytes:number;source:string;features:Record<string,number|string|boolean>|null }
type ImportResult = { id:number;filename:string;imported_at:string;total_rows:number;accepted_rows:number;rejected_rows:number;errors:{row:number;reason:string}[] }
type DatasetProfile = {samples:number;engineered_samples:number;feature_count:number;feature_schema:string;labels_available:boolean;limitations:string}
const nav = [
  ['Overview', Gauge], ['SECURITY OPERATIONS', null], ['Alerts', ShieldAlert], ['Incidents', Boxes], ['Network Events', RadioTower],
  ['DETECTION', null], ['Detection Rules', FileSearch], ['MITRE ATT&CK', Hexagon], ['AI & EXPLAINABILITY', null],
  ['Explainability', Activity], ['Model Predictions', CircleDot], ['AI Assistant', Bot], ['RESEARCH', null],
  ['Experiments', Beaker], ['Model Comparison', Activity], ['Dataset', Database], ['Error Analysis', AlertTriangle], ['Model Monitoring', Gauge],
  ['SYSTEM', null], ['Settings', Settings],
] as const
const severityColor:Record<string,string> = { Critical:'#ef4444', High:'#f97316', Medium:'#f59e0b', Low:'#3b82f6', Informational:'#64748b' }

function Sidebar({open,onClose,active,onNavigate}:{open:boolean;onClose:()=>void;active:string;onNavigate:(page:string)=>void}){ return <><button className={`sidebar-backdrop ${open?'visible':''}`} onClick={onClose} aria-label="Close navigation"/><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark"><ShieldCheck size={22}/></div><div><strong>SENTINEL XAI</strong><span>SOC ASSISTANT</span></div><button className="close-nav" onClick={onClose} aria-label="Close navigation"><X size={19}/></button></div><nav>{nav.map(([label,Icon])=>Icon?<button className={label===active?'active':''} key={label} onClick={()=>{onNavigate(label);onClose()}}><Icon size={16}/><span>{label}</span>{label==='Alerts'&&<b>4</b>}</button>:<p key={label}>{label}</p>)}</nav><div className="system"><i></i><div><strong>LOCAL SYSTEM</strong><span>Evidence pipeline online</span></div></div></aside></> }
function Metric({label,value,icon:Icon,tone}:{label:string,value:string|number,icon:any,tone:string}){return <article className="metric"><div><span>{label}</span><strong>{value}</strong></div><div className="metric-icon" style={{color:tone,background:`${tone}18`}}><Icon size={20}/></div></article>}
const shortTime=(v:string)=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})

function EventsPage(){
 const queryClient=useQueryClient()
 const [selectedFile,setSelectedFile]=useState<File|null>(null)
 const [result,setResult]=useState<ImportResult|null>(null)
 const events=useQuery<NetworkEvent[]>({queryKey:['events'],queryFn:async()=>{const r=await fetch(`${API}/events?limit=100`);if(!r.ok)throw new Error('Could not load events');return r.json()}})
 const imports=useQuery<ImportResult[]>({queryKey:['imports'],queryFn:async()=>{const r=await fetch(`${API}/imports`);if(!r.ok)throw new Error('Could not load imports');return r.json()}})
 const profile=useQuery<DatasetProfile>({queryKey:['dataset-profile'],queryFn:async()=>{const r=await fetch(`${API}/research/dataset`);if(!r.ok)throw new Error('Could not load dataset profile');return r.json()}})
 const upload=useMutation({mutationFn:async(file:File)=>{const form=new FormData();form.append('file',file);const r=await fetch(`${API}/events/import`,{method:'POST',body:form});if(!r.ok){const body=await r.json().catch(()=>null);throw new Error(typeof body?.detail==='string'?body.detail:body?.detail?.message||'Import failed')}return r.json() as Promise<ImportResult>},onSuccess:async(data)=>{setResult(data);setSelectedFile(null);await Promise.all([queryClient.invalidateQueries({queryKey:['events']}),queryClient.invalidateQueries({queryKey:['imports']}),queryClient.invalidateQueries({queryKey:['dataset-profile']}),queryClient.invalidateQueries({queryKey:['dashboard']})])}})
 return <div className="events-page">
  <section className="dataset-strip"><div><span>EVENT STORE</span><strong>{profile.data?.samples??'—'}</strong><small>Total records</small></div><div><span>FEATURE PIPELINE</span><strong>{profile.data?.engineered_samples??'—'}</strong><small>Engineered records</small></div><div><span>SCHEMA</span><strong>{profile.data?.feature_schema??'flow-v1'}</strong><small>{profile.data?.feature_count??12} deterministic features</small></div><div><span>GROUND TRUTH</span><strong className="unavailable">Unavailable</strong><small>No labels inferred</small></div></section>
  <section className="events-layout"><article className="panel upload-panel"><div className="panel-head"><div><span>DATA INGESTION</span><h2>Import network-flow CSV</h2></div><FileUp size={20}/></div><p className="panel-copy">Upload UTF-8 flow records. Every row is validated and the original evidence is retained alongside deterministic features.</p><label className={`dropzone ${selectedFile?'has-file':''}`}><input type="file" accept=".csv,text/csv" onChange={e=>{setSelectedFile(e.target.files?.[0]||null);setResult(null);upload.reset()}}/><UploadCloud size={28}/>{selectedFile?<><strong>{selectedFile.name}</strong><span>{(selectedFile.size/1024).toFixed(1)} KB · ready to validate</span></>:<><strong>Choose a CSV file</strong><span>Required: timestamp, IPs, ports, protocol, duration, packets, bytes · max 5 MB</span></>}</label><button className="primary-action" disabled={!selectedFile||upload.isPending} onClick={()=>selectedFile&&upload.mutate(selectedFile)}>{upload.isPending?'Validating and importing…':'Import events'}</button>{upload.error&&<div className="import-message failed"><XCircle size={17}/><span>{upload.error.message}</span></div>}{result&&<div className="import-message success"><CheckCircle2 size={17}/><div><strong>{result.accepted_rows} rows imported</strong><span>{result.rejected_rows?`${result.rejected_rows} rejected with traceable reasons`:'No rows rejected'}</span></div></div>}</article>
  <article className="panel import-history"><div className="panel-head"><div><span>PROVENANCE</span><h2>Recent imports</h2></div></div>{imports.data?.length?imports.data.slice(0,5).map(item=><div className="import-row" key={item.id}><div className="file-icon"><FileUp size={16}/></div><div><strong>{item.filename}</strong><span>{new Date(item.imported_at).toLocaleString()}</span></div><div className="import-count"><strong>{item.accepted_rows}</strong><span>accepted</span></div>{item.rejected_rows>0&&<b>{item.rejected_rows} rejected</b>}</div>):<div className="empty-state">No CSV imports yet. Synthetic seed events remain clearly separated.</div>}</article></section>
  <section className="panel events-table"><div className="panel-head"><div><span>RAW EVIDENCE</span><h2>Network events</h2></div><span className="record-count">{events.data?.length??0} shown</span></div><div className="table-wrap"><table><thead><tr><th>TIME</th><th>SOURCE</th><th>DESTINATION</th><th>PROTOCOL</th><th>PACKETS</th><th>BYTES</th><th>PROVENANCE</th><th>FEATURES</th></tr></thead><tbody>{events.data?.map(event=><tr key={event.id}><td data-label="Time">{new Date(event.timestamp).toLocaleString()}</td><td data-label="Source"><strong>{event.src_ip}</strong>:{event.src_port}</td><td data-label="Destination"><strong>{event.dst_ip}</strong>:{event.dst_port}</td><td data-label="Protocol"><code>{event.protocol}</code></td><td data-label="Packets">{event.packets.toLocaleString()}</td><td data-label="Bytes">{event.bytes.toLocaleString()}</td><td data-label="Provenance"><span className={event.source.startsWith('CSV_IMPORT:')?'source imported':'source synthetic'}>{event.source.startsWith('CSV_IMPORT:')?'CSV import':'Synthetic demo'}</span></td><td data-label="Features">{event.features?<span className="feature-ready"><CheckCircle2 size={13}/> Ready</span>:<span className="na">Not processed</span>}</td></tr>)}</tbody></table></div></section>
  <div className="research-note"><ShieldCheck size={18}/><span>{profile.data?.limitations||'Imported events remain unlabeled until a real experiment supplies ground truth.'}</span></div>
 </div>
}

const pageMilestones:Record<string,{milestone:string;description:string}>={
 Alerts:{milestone:'Milestone 4',description:'Alert triage, status changes, assignments, and evidence-first investigation.'},
 Incidents:{milestone:'Milestone 6',description:'Transparent alert correlation, timelines, affected assets, and analyst notes.'},
 'Detection Rules':{milestone:'Milestone 4',description:'Deterministic security rules with explicit evidence and version history.'},
 'MITRE ATT&CK':{milestone:'Milestone 6',description:'Evidence-backed potential technique mappings with confidence and reasons.'},
 Explainability:{milestone:'Milestone 5',description:'Global and local SHAP explanations derived from trained model outputs.'},
 'Model Predictions':{milestone:'Milestone 3',description:'Model outputs, probabilities, versions, and inference metadata.'},
 'AI Assistant':{milestone:'Milestone 8',description:'Optional grounded assistance using only stored alert and incident evidence.'},
 Experiments:{milestone:'Milestone 3',description:'Reproducible training runs with datasets, parameters, features, and real metrics.'},
 'Model Comparison':{milestone:'Milestone 3',description:'Precision, recall, F1, ROC-AUC, PR-AUC, and timing comparisons.'},
 Dataset:{milestone:'Milestone 2',description:'Dataset composition, source provenance, feature schema, and limitations.'},
 'Error Analysis':{milestone:'Milestone 7',description:'False-positive and false-negative examples linked to model explanations.'},
 'Model Monitoring':{milestone:'Milestone 8',description:'Prediction distributions, feature drift, feedback, and model versions over time.'},
 Settings:{milestone:'System',description:'Local provider, storage, CORS, upload-limit, and runtime configuration.'},
}

function PlannedPage({name,onBack}:{name:string;onBack:()=>void}){
 const page=pageMilestones[name]||{milestone:'Planned',description:'This workspace is reserved for a future implementation milestone.'}
 return <section className="planned-page"><div className="planned-icon"><Boxes size={27}/></div><span>{page.milestone.toUpperCase()}</span><h2>{name}</h2><p>{page.description}</p><div className="planned-honesty"><ShieldCheck size={16}/><div><strong>Not implemented yet</strong><small>This page is intentionally not populated with fabricated functionality or data.</small></div></div><button onClick={onBack}>Return to overview</button></section>
}

export default function App(){
 const [navOpen,setNavOpen]=useState(false)
 const [activePage,setActivePage]=useState('Overview')
 const {data,error,isLoading}=useQuery<Dashboard>({queryKey:['dashboard'],queryFn:async()=>{const r=await fetch(`${API}/dashboard`);if(!r.ok)throw new Error('API unavailable');return r.json()}})
 const fallback:Dashboard={data_label:'SYNTHETIC DEMO DATA',metrics:{active_alerts:0,critical_alerts:0,high_alerts:0,open_incidents:0,events_analyzed:0,average_model_confidence:null},alerts_by_severity:{Critical:0,High:0,Medium:0,Low:0,Informational:0},alerts_by_protocol:[],alerts_over_time:[],recent_alerts:[]}
 const d=data||fallback; const severityData=Object.entries(d.alerts_by_severity).map(([name,value])=>({name,value})).filter(x=>x.value)
 const isEvents=activePage==='Network Events'
 const isOverview=activePage==='Overview'
 const sectionLabel=isEvents?'INGESTION & EVIDENCE':isOverview?'SECURITY OPERATIONS':pageMilestones[activePage]?.milestone||'PLANNED WORKSPACE'
 const pageTitle=isEvents?'Network events':isOverview?'Command overview':activePage
 const pageDescription=isEvents?'Import, validate, and inspect network-flow evidence':isOverview?'Evidence-led monitoring across your network environment':pageMilestones[activePage]?.description||'Planned research workspace'
 return <div className="app"><Sidebar open={navOpen} onClose={()=>setNavOpen(false)} active={activePage} onNavigate={setActivePage}/><main><header><div className="title-wrap"><button className="menu-button" onClick={()=>setNavOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><div><span className="eyebrow">{sectionLabel}</span><h1>{pageTitle}</h1><p>{pageDescription}</p></div></div><div className="header-actions"><button className="search"><Search size={17}/><span>Search events, alerts, IPs</span><kbd>⌘ K</kbd></button><button className="live"><i/> LIVE</button><div className="avatar">AN</div></div></header>
 {isEvents?<EventsPage/>:!isOverview?<PlannedPage name={activePage} onBack={()=>setActivePage('Overview')}/>:<>
 <div className="demo"><Beaker size={16}/><strong>{d.data_label}</strong><span>Illustrative events and deterministic rule evidence only. No trained model metrics are displayed.</span></div>
 {error&&<div className="error">Backend unavailable. Start the API to load demo evidence.</div>}
 <section className="metrics"><Metric label="ACTIVE ALERTS" value={isLoading?'—':d.metrics.active_alerts||0} icon={ShieldAlert} tone="#60a5fa"/><Metric label="CRITICAL" value={d.metrics.critical_alerts||0} icon={AlertTriangle} tone="#ef4444"/><Metric label="HIGH SEVERITY" value={d.metrics.high_alerts||0} icon={Activity} tone="#f97316"/><Metric label="OPEN INCIDENTS" value={d.metrics.open_incidents||0} icon={Boxes} tone="#a78bfa"/><Metric label="EVENTS ANALYZED" value={d.metrics.events_analyzed||0} icon={RadioTower} tone="#22d3a6"/></section>
 <section className="charts"><article className="panel wide"><div className="panel-head"><div><span>DETECTION ACTIVITY</span><h2>Alerts over time</h2></div><button>Last 24 hours⌄</button></div><ResponsiveContainer width="100%" height={220}><AreaChart data={d.alerts_over_time}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3b82f6" stopOpacity={.35}/><stop offset="1" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1b2638" vertical={false}/><XAxis dataKey="time" stroke="#64748b" tickLine={false}/><YAxis stroke="#64748b" allowDecimals={false} tickLine={false}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/><Area type="monotone" dataKey="alerts" stroke="#60a5fa" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></article>
 <article className="panel"><div className="panel-head"><div><span>RISK PROFILE</span><h2>Alerts by severity</h2></div></div><div className="donut"><ResponsiveContainer width="52%" height={190}><PieChart><Pie data={severityData} dataKey="value" innerRadius={57} outerRadius={78} paddingAngle={3}>{severityData.map(x=><Cell key={x.name} fill={severityColor[x.name]}/>)}</Pie><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/></PieChart></ResponsiveContainer><div className="legend">{severityData.map(x=><div key={x.name}><i style={{background:severityColor[x.name]}}/><span>{x.name}</span><b>{x.value}</b></div>)}</div></div></article>
 <article className="panel"><div className="panel-head"><div><span>TRAFFIC CONTEXT</span><h2>Alerts by protocol</h2></div></div><ResponsiveContainer width="100%" height={190}><BarChart data={d.alerts_by_protocol} layout="vertical"><CartesianGrid stroke="#1b2638" horizontal={false}/><XAxis type="number" stroke="#64748b" allowDecimals={false}/><YAxis dataKey="name" type="category" stroke="#94a3b8" width={45}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #263348'}}/><Bar dataKey="value" fill="#22d3a6" radius={[0,5,5,0]} barSize={18}/></BarChart></ResponsiveContainer></article></section>
 <section className="panel table-panel"><div className="panel-head"><div><span>INVESTIGATION QUEUE</span><h2>Recent alerts</h2></div><button className="link">View all alerts <ChevronRight size={15}/></button></div><div className="table-wrap"><table><thead><tr><th>TIME</th><th>SEVERITY</th><th>NETWORK PATH</th><th>PROTOCOL</th><th>DETECTION & EVIDENCE</th><th>CONFIDENCE</th><th>STATUS</th><th></th></tr></thead><tbody>{d.recent_alerts.map(a=><tr key={a.id}><td data-label="Time">{shortTime(a.timestamp)}</td><td data-label="Severity"><span className={`badge ${a.severity.toLowerCase()}`}><i/>{a.severity}</span></td><td data-label="Network path"><strong>{a.source}</strong><span className="arrow">→</span>{a.destination}:{a.destination_port}</td><td data-label="Protocol"><code>{a.protocol}</code></td><td data-label="Detection"><strong>{a.detection}</strong><small>Deterministic demo rule</small></td><td data-label="Confidence">{a.model_probability===null?<span className="na">Not ML</span>:`${Math.round(a.model_probability*100)}%`}</td><td data-label="Status"><span className="status">{a.status}</span></td><td className="row-arrow"><ChevronRight size={16}/></td></tr>)}{!d.recent_alerts.length&&<tr><td colSpan={8} className="empty">{isLoading?'Loading evidence…':'No alerts available.'}</td></tr>}</tbody></table></div></section>
 <footer><span>Milestone 2 · Validated ingestion and feature pipeline</span><span>Model metrics: <b>not yet available</b></span></footer></>}
 </main></div>
}
